//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Squirrel.Domain.Resources.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SquirrelResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SquirrelResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Squirrel.Domain.Resources.Resources.SquirrelResources", typeof(SquirrelResources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bagno.
        /// </summary>
        public static string BathRoom {
            get {
                return ResourceManager.GetString("BathRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Camera.
        /// </summary>
        public static string BedRoomName {
            get {
                return ResourceManager.GetString("BedRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Giardino.
        /// </summary>
        public static string Garden {
            get {
                return ResourceManager.GetString("Garden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingresso.
        /// </summary>
        public static string HallName {
            get {
                return ResourceManager.GetString("HallName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cucina.
        /// </summary>
        public static string KitchenName {
            get {
                return ResourceManager.GetString("KitchenName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soggiorno.
        /// </summary>
        public static string LivingRoomName {
            get {
                return ResourceManager.GetString("LivingRoomName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Studio.
        /// </summary>
        public static string OfficeName {
            get {
                return ResourceManager.GetString("OfficeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SquirrelContainer.
        /// </summary>
        public static string SquirrelContainerName {
            get {
                return ResourceManager.GetString("SquirrelContainerName", resourceCulture);
            }
        }
    }
}
